export {default as Home} from "./Home";
export {default as Login} from "./Login";
export {default as Register} from "./Register";
export {default as Navbar} from "./navbar";
export {default as Footer} from "./Footer";
export {default as Shop} from "./Shop";
export {default as SimpleCartMenu} from "./SimpleCartMenu";
export {default as AddToCartButton} from "./AddToCartButton"
export {default as SingleProduct} from "./SingleProduct"
